# make docker compose
version: "3.3"

# make docker compose config from notes_app images
services:
  web:
    build: .
    ports:
      - "3000:3000"
    # environment variables from .env
    env_file:
      - .env
    # add env prod
    environment:
      - ENV=production
