// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlcpg

import (
	"context"
	"database/sql"
)

type Querier interface {
	FindUser(ctx context.Context, id int32) (User, error)
	FindUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	FindUserByPhoneNumber(ctx context.Context, phoneNumber sql.NullString) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
	FindUserByUsernameOrEmailOrPhoneNumber(ctx context.Context, arg FindUserByUsernameOrEmailOrPhoneNumberParams) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	Login(ctx context.Context, arg LoginParams) (User, error)
	Register(ctx context.Context, arg RegisterParams) (User, error)
}

var _ Querier = (*Queries)(nil)
